### PR TITLE
Add Trusted Types (#20) as 'defer'.

### PR DESCRIPTION
**Pull request by dbaron**

### CODE REVIEW

**Comment by mikewest** [comment]
After the conversations we've had recently, I thought we'd ended up with a reasonable direction for the mechanism that y'all could, at least in theory, get on board with. I was hopeful that Mozilla would come down on "worth prototyping" or at least "non-harmful". Though I'm happy to see you haven't chosen "harmful", it surprises me a bit that y'all would end up punting the question.

+@annevk, +@jonathanKingston

**Comment by dbaron** [comment]
Please have the discussion about what the position should be in #20 rather than here.

(It sounds like that discussion hasn't been reflected over there.)

**Comment by mikewest** [comment]
@annevk, @jonathanKingston: Perhaps one of you could update the thread in #20 with your takeaways from our most recent discussion?

**Comment by annevk** [comment]
Sorry about that, https://github.com/mozilla/standards-positions/issues/20#issuecomment-555016682.

**Comment by dbaron** [comment]
I'll make a new PR for whatever we decide there.

**Pull request closed without merging**
