### PR TITLE
defer Media Queries 5 until CR

### LINKED ISSUE #389: CSS Media Queries Level 5
## Request for Mozilla Position on an Emerging Web Specification

  * Specification Title: Media Queries Level 5
  * Specification or proposal URL: https://drafts.csswg.org/mediaqueries-5/
  * Caniuse.com URL (optional):
  * Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1434491
  * Mozillians who can provide input (optional): @heycam, @dbaron
  * W3C Tag Design Review issue: none

### Other information

We have implemented several of the features in Media Queries Level 5: [prefers-reduced-motion](https://bugzilla.mozilla.org/show_bug.cgi?id=1434491), [prefers-color-scheme](https://bugzilla.mozilla.org/show_bug.cgi?id=1494034), and most recently, [prefers-contrast](https://bugzilla.mozilla.org/show_bug.cgi?id=1506364) (as [announced Monday](https://wiki.mozilla.org/Firefox/Roadmap/Updates#2020-07-06)).

In general Media Queries Level 5 has several accessibility enhancing features and thus we should consider an overall status of "important".

Label: w3c.

(Originally published at: https://tantek.com/2020/191/b2/)

### PR DESCRIPTION
**Pull request by tantek**
Closes #389. We will evaluate specific features individually or related sets of features instead until MQ5 reaches CR, and then we can re-open #389 for re-evaluation.

### CODE REVIEW

**Comment by annevk** [comment]
Given the third bullet point in https://www.w3.org/2019/Process-20190301/#candidate-rec wouldn't that be a tad to late?

**Comment by dbaron** [comment]
What I was suggesting in #389 was that we should not have "Mediaqueries 5" as an entry in the table at all; instead we should have features at the scope that we would make decisions about whether they're worthwhile or not.  CSS modules, particularly for additions to mature features, tend to be a grab bag of features of totally different value and priority, so I think we should probably avoid trying to prioritize them as a whole.  (Probably when we listed [CSS Grid Layout Module Level 2](https://mozilla.github.io/standards-positions/#subgrid) we should really have listed "subgrid", which is actually what we meant when we marked it as `important`.  It's even in the ID!)

**Comment by martinthomson** [comment]
It might then be better to say "css-accessibility-media-queries" or "css-mq5-accessibility" as the target of this and say "worth prototyping".

**Comment by dbaron** [comment]
Closing in favor of resolving #393 instead, as I suggested above.

**Pull request closed without merging**
