### PR TITLE
Position on exception handling, closes #573

### LINKED ISSUE #573: Request for Position: WebAssembly Exception Handling
## Request for Mozilla Position on WebAssembly Exception Handling

* Specification Title: Exception Handling Proposal for WebAssembly
* Specification or proposal URL: https://github.com/WebAssembly/exception-handling
* Caniuse.com URL (optional): none
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1695715
* Mozillians who can provide input (optional): @lars-t-hansen

### PR DESCRIPTION
**Pull request by lars-t-hansen**
We support it.

### CODE REVIEW

**Review by tantek — CHANGES_REQUESTED** [review]
I looked at #573 and it's a bit thin. Could you add reasoning to that issue? 

I.e. *why* do we think this is "important" vs "worth prototyping"?

Is the problem being solved "important" and the solution is a good solution from our perspective?

What does "we support it" mean in this context? Does it mean we've already implemented it, or that we are generally supportive of this effort?

**Comment by lars-t-hansen** [comment]
@tantek, updated #573, PTAL.

**Review by tantek — CHANGES_REQUESTED** [review]
Thanks for the comment on #573, that takes care of that!

In looking closer at this PR, since it's a proposal in a CG (not a WD in a WG) we either need to
in "org": s/W3C/Proposal
or
land exception handling in a Working Draft published by the WebAssembly Working Group and change the "url" to that.

**Comment by lars-t-hansen** [comment]
It was easier to update the Org than to push this into the WG; the WG tends not to look at all until the thing is in Phase 4.

**Review by tantek — APPROVED** [review]
SGTM

**Pull request merged**
