### PR TITLE
Dark mode dashboard

### LINKED ISSUE #814: Dark mode on your website
this is not a request for Mozilla Position on an Emerging Web Specification
but a request for https://mozilla.github.io/standards-positions/ to support dark mode.

The site is too bright at night.

and hopefully also make use of `color-scheme` with either of this solutions:

`<meta name="color-scheme" content="dark light">`
```css
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
  }
}
```

- https://web.dev/color-scheme/

### PR DESCRIPTION
**Pull request by martinthomson**
This isn't so trivial, but likely only because I don't know how to drive bootstrap.  This just overrides the rules for stuff we use.

Feedback on color choice welcome; I just picked something that looked OK on my screen.

Closes #814.

### CODE REVIEW

**Comment by martinthomson** [comment]
Example:
image

**Comment by zcorpan** [comment]
This looks OK I think (but I'm not a designer). Maybe `mark` should have different colors?

I was also going to suggest to check for color contrast issues (with Accessibility Inspector), but light mode already has some issues there so could be a follow-up.

**Comment by bgrins** [comment]
Looks like if we were using bootstrap >= 5.3 there's some built in support for dark theme and custom variables that could be set: https://getbootstrap.com/docs/5.3/customize/color-modes/. Upgrading to a new version may be more work than this patch though

**Comment by zcorpan** [comment]
This is no longer relevant, see #1063.

**Pull request closed without merging**
