### PR TITLE
Positive: Opaque Response Blocking (ORB)

### LINKED ISSUE #860: Opaque Response Blocking
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Opaque Response Blocking
* Specification or proposal URL (if available):  https://github.com/annevk/orb
* Explainer URL (if available): 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1532642
* Mozillians who can provide input (optional): @zcorpan @sefeng211 @farre 

### Other information
* There's a PR open which has the actual changes to the Fetch spec: https://github.com/whatwg/fetch/pull/1442
* ORB has been enabled on [Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1800658) and [early beta](https://bugzilla.mozilla.org/show_bug.cgi?id=1821682) on Firefox.
* Chrome's intent-to-ship for ORB [v0.1](https://groups.google.com/a/chromium.org/g/blink-dev/c/ScjhKz3Z6U4/m/5i_0V7ogAwAJ) and [v0.2](https://groups.google.com/a/chromium.org/g/blink-dev/c/RcuAzHEI2CU/m/E37KLjZjCwAJ) 
* Also see https://github.com/mozilla/standards-positions/issues/81#issuecomment-613937108

### PR DESCRIPTION
**Pull request by farre**
We closed this without a dashboard entry, but it seems like we'd benefit from one.

Closes #860.

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]
Simple.

**Comment by martinthomson** [comment]
@farre, would you mind sorting the file?  I know you put this next to CORB, but the validation script wants entries sorted by title.

**Comment by farre** [comment]
Sure, I'm on it.

**Comment by farre** [comment]
@martinthomson more like this?

**Comment by martinthomson** [comment]
Yes, exactly like that.  Thanks!

**Pull request merged**
