### PR TITLE
Update Serial position

### PR DESCRIPTION
**Pull request by bgrins**

### CODE REVIEW

**Comment by bgrins** [comment]
Fixes #687

**Review by tantek — APPROVED** [review]
I think this accurately reflects our updated experience and more cautious method for approaching these sorts of specifications. Approving without merging to get more reviews because this is a more long-running / sensitive shift than usual.

**Comment by bholley** [comment]
LGTM

**Comment by Ferdi265** [comment]
With this merged, will Mozilla reconsider their stance of not implementing WebSerial (as per [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=webserial)) and potentially implement it in a similar add-on gated way to WebMIDI?

**Comment by bholley** [comment]
> With this merged, will Mozilla reconsider their stance of not implementing WebSerial (as per [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=webserial)) and potentially implement it in a similar add-on gated way to WebMIDI?

This PR represents a reconsideration of our stance. We'd take a patch, assuming we think the proposed language in the prompt is sufficiently clear and assuming the patch otherwise met all of our usual standards.

**Comment by nyabinary** [comment]
> With this merged, will Mozilla reconsider their stance of not implementing WebSerial (as per [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=webserial)) and potentially implement it in a similar add-on gated way to WebMIDI?

The bug should be reopened though as tracking though at least, right?

**Pull request merged**
