### PR TITLE
Import Maps (worth prototyping)

### LINKED ISSUE #146: Import maps
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Import maps
* Specification or proposal URL: https://github.com/WICG/import-maps
* Mozillians who can provide input (optional): @lukewagner @tschneidereit @linclark @callahad

This rather fundamentally impacts all fetching infrastructure and it's the way you'd polyfill lack of support for a JavaScript built-in module.

(It doesn't really feel like a primitive however as it's not necessarily available before the first fetch (e.g., one from a `Link` header), though perhaps if we'd delay those that could be made to work.)

### PR DESCRIPTION
**Pull request by codehag**
cc @moztcampbell and @annevk.

Closes #146

### CODE REVIEW

**Review by tantek — CHANGES_REQUESTED** [review]
I don't disagree with this summary, however we (perhaps you Yulia?) really should first comment with a more thorough conclusion of why "We support the overall intent", in issue #146 so that the reasoning is captured there, and in particular as a clear reply to Dominic's request for an update from Mozilla. Then we can give it a few days (week?) for any dissent/confirmation to be expressed from Mozilla folks (@annevk ?) and then if that goes well we can merge this.

**Review by tantek — APPROVED** [review]
Thanks for the comment on #146! LGTM. Let's get a +1 from @annevk then merge.

**Review by annevk — APPROVED** [review]

**Comment by benwiley4000** [comment]
Sorry if this is written somewhere obvious, but is there a way to track the actual progress of this prototype? I have some integration tests for my app can only run with Chrome until the import map feature is available in Firefox and I'd be excited to try it out when an early version is ready.

**Comment by myakura** [comment]
@benwiley4000 

> Sorry if this is written somewhere obvious, but is there a way to track the actual progress of this prototype? I have some integration tests for my app can only run with Chrome until the import map feature is available in Firefox and I'd be excited to try it out when an early version is ready.

you might want to check out https://bugzilla.mozilla.org/show_bug.cgi?id=1688879 , which is linked from the position entry https://mozilla.github.io/standards-positions/#import-maps

**Pull request merged**
