### PR TITLE
Add the most active issues as "under consideration".

### PR DESCRIPTION
**Pull request by dbaron**
These issues seem worth trying to resolve first, and as part of being
more public about that discussion, I'm going to explicitly list them as
"under consideration" and reference their issues.

This will thus link to #58, #27, #24, and #19.

It also happens to include the first links to caniuse (the "ciuName"
field being non-null).

Note that activities.py normalized some whitespace in a prior entry
added in #53.  (I should figure out why it's always adding a space at
the end of the line, but that's a separate issue.  Until then, I'd
rather keep the file matching the way activities.py regenerates it
rather than having to hand-edit every time to avoid changing those
lines.)

### CODE REVIEW

**Comment by martinthomson** [comment]
permissions-api mozPosition: remains complicated because that covers more than just `query()`

**Comment by dbaron** [comment]
I'm actually hesitating about the bug URLs, because I'm a little hesitant to drive traffic to bugs.

**Comment by dbaron** [comment]
I guess I should add the bugs at least, for the one that are in fact clearly metabugs for the entire spec.  I'm inclined to omit those that aren't.  I'll go through them later...

**Comment by tantek** [comment]
<https://github.com/martinthomson> wrote:

> that covers more than just query()

In that case, shouldn’t we re-open <https://bugzilla.mozilla.org/show_bug.cgi?id=1105827>, and file new dependent bugs for what is not yet implemented / covered?

<https://github.com/dbaron> wrote:

> hesitating about the bug URLs, because I'm a little hesitant to drive traffic to bugs

Makes sense. Worth adding to this project readme/how-to officially? As in something like:

“The mozBugUrl field should only be filled in for "worth prototyping" or "important" standards, to avoid misdirecting higher-level discussion traffic to the bugs, which should be focused on implementation-specific discussions.”

(Originally published at: http://tantek.com/2018/064/t1/)

**Comment by dbaron** [comment]
> In that case, shouldn’t we re-open <https://bugzilla.mozilla.org/show_bug.cgi?id=1105827>, and file new dependent bugs for what is not yet implemented / covered?

It's better not to repurpose bugs; the history becomes unreadable, and regression/dependency tracking becomes unusable.  If needed, a new bug should be filed, and if needed the old one could be retitled.

**Pull request merged**
