### PR TITLE
Update Web Share and Web Share Target positions

### LINKED ISSUE #27: Web Share API
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Web Share API
* Specification or proposal URL: https://wicg.github.io/web-share/

### Other information
Currently behind a flag in Chrome as an "origin trial".

This specification defines an API for sharing text, links and other content to an arbitrary destination of the user's choice. The available share targets are not specified here; they are provided by the user agent. They could, for example, be apps, websites or contacts.

### LINKED ISSUE #176: Web Share Target
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Web Share Target
* Specification or proposal URL:  https://wicg.github.io/web-share-target/
* Mozillians who can provide input (optional): @tantek @NotWoods

### Other information
An API that allows websites to declare themselves as web share targets, which can receive shared content from either the Web Share API (see #27), or system events (e.g., shares from native apps).

cc @mgiuca

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #27 
closes #176

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@dbaron, ping. Web Share itself is ready to land behind a pref:
https://phabricator.services.mozilla.com/D44598

**Comment by dbaron** [comment]
Sorry for the delay @marcoscaceres -- I'm back from vacation now.

One concern about this PR is that it updates the position on Web Share to `important` without any discussion of that change in #27.  Could you discuss that particular change there?

It might also be worth writing a little bit of text in the `mozPositionDetail` explaining why these specifications are worth prototyping or important.

**Comment by marcoscaceres** [comment]
I'll defer to the product owners to provide positions, as they are in charge of adding these to Firefox.

**Comment by marcoscaceres** [comment]
> One concern about this PR is that it updates the position on Web Share to important without any discussion of that change in #27. Could you discuss that particular change there?

@dbaron, I added some thoughts of why I think it's important - hopefully other folks will chime in.  The feature is already in Fenix, so hopefully we can reach a position before it ships. I imagine the Fenix team will send an "intent to ship" at some point.  

https://github.com/mozilla/standards-positions/issues/27#issuecomment-559345271

**Pull request closed without merging**
